spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tzxblog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: tuzongxun
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      allow-pool-suspension: true
      max-lifetime: 300000
      login-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 30000
      idle-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: HikariCP
      connection-test-query: SELECT 1
      auto-commit: true
      read-only: false

mybatis-plus:
  mapper-locations: classpath:com/tzx/blog/dao/mapper/*.xml
  #mybatis
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tzx.blog.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
imgs:
  filepath: E:/img/
  host: localhost
  port: 8089